import type { Metadata } from "next";
import Script from "next/script";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";

const instagramSans = localFont({
  variable: "--font-instagram-sans",
  src: [
    { path: "../../public/instagram-sans-2/Instagram Sans Light.ttf", weight: "300", style: "normal" },
    { path: "../../public/instagram-sans-2/Instagram Sans.ttf", weight: "400", style: "normal" },
    { path: "../../public/instagram-sans-2/Instagram Sans Medium.ttf", weight: "500", style: "normal" },
    { path: "../../public/instagram-sans-2/Instagram Sans Bold.ttf", weight: "700", style: "normal" },
    { path: "../../public/instagram-sans-2/Instagram Sans Headline.otf", weight: "800", style: "normal" },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instagramSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var e="theme",t=localStorage.getItem(e)||"dark";if(t==="system"){t=window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}var r=document.documentElement;r.classList.toggle("dark",t==="dark");r.style.colorScheme=t}catch(n){}})();`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
